spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 2000ms
  application:
    name: hansen-village-application
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:looneyhardy@gmail.com}
    password: ${MAIL_PASSWORD:ijmkjkfkdwgwolqy}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
#          starttls:
#            enable: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

store:
  jwt:
    secret: ${STORE_JWT_SECRET}
    expiration-ms: ${STORE_JWT_EXPIRATION_MS}
    refresh-expiration-ms: ${STORE_JWT_REFRESH_EXPIRATION_MS}

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.liquibase: INFO