version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-hansen
    restart: unless-stopped
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPass
      POSTGRES_DB: hansen-village
    ports:
      - "5432:5432"
    volumes:
      - postgres_hansen_data:/var/lib/postgresql/data

volumes:
  postgres_hansen_data:
    name: postgres_hansen_data